Dockerfile
Dockerfile_builder
entrypoint.sh

feat: add osx-cross builder with supporting macOS SDK 10.15

---

.github/workflows/builder.yml
.github/workflows/dockerimage.yml

Initial work to update `golang-cross-builder` image to use go 1.17.1
Follow up PRs:
- update the base image in the golang-cross
- update readme
/assign @gythialy

update workflow to build golang-cross-builder 1.17.1

---

Dockerfile

install cosign

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

go: update to go 1.17.3

---

Dockerfile

feat: verify checksum.txt for goreleaser

---

Dockerfile

feat: install ko

---

Dockerfile

chore: update flag for cosign &  update base image

chore: update flag for cosign & update base image

---

Dockerfile

feat: install gcloud sdk

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile

update buildx to v0.7.0

---

Dockerfile

feat: upgrade cosign to 1.3.1, goreleaser to 1.1.0

---

Dockerfile

let's wait until they release v1.4.1 because there are some bugs in v1.4.0. 👇
https://sigstore.slack.com/archives/C01PZKDL4DP/p1638843956463600

feat: upgrade cosign to v1.4.1

---

Dockerfile

- fix the public key to check the signature

fix the public key to check the signature

---

Dockerfile

- add syft to the image
to use together with goreleaser to generate the sboms

add syft to the image

---

Dockerfile

update goreleaser to 1.2.2

---

.github/workflows/builder.yml
Dockerfile.builder

add s390x to the builder

---

.github/dependabot.yml
.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- update golang to 1.17.6 
- update goreleaser to 1.2.5 
- update buildx to 0.7.1

Update go to 1.17.6

---

.github/workflows/builder.yml
Dockerfile.builder

Add cross essentials s390x

---

Dockerfile

update base builder image

---

Dockerfile

feat(goreleaser): upgrade gorelease version to 1.3.1

---

Dockerfile

chore: upgrade syft 0.36.0

---

Dockerfile

update cosign to 1.5.1

---

Dockerfile

chore: upgrade goreleaser to v1.4.1

---

Dockerfile

install goimports

---

Dockerfile

feat: upgrade goreleaser v1.5.0

---

Dockerfile

- update ko to release v0.10.0

update ko to release v0.10.0

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- update go to 1.17.8
go annoucement: https://groups.google.com/g/golang-announce/c/RP1hfrBYVuk/m/I7ouYouLAAAJ

update go to 1.17.8

---

Dockerfile

feat: upgrade cosign to v1.6.0 and syft to v0.40.0

---

Dockerfile

feat: upgrade syft to v0.41.1

---

Dockerfile

feat: upgrade goreleaser to 1.6.3

---

.github/workflows/builder.yml
.github/workflows/dockerimage.yml
.github/workflows/release-golang-cross.yml
Dockerfile
Dockerfile.builder
README.md

- disable docker.pkg.github.com to fix #103 
- bump Debian version to bullseye
- cherry pick 538403c404426f206038095225ce2f6b9adc05f2
- bump golang version to v1.18

refactor: build image scripts

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile

update action and cosign image to use 1.8.0 release on the main branch

update action and cosign image to use 1.8.0 release

---

Dockerfile

feat: upgrade goreleaser to 1.8.3, syft to 0.45.1 

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

update golang to go 1.17.10

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

update go to 1.18.2

---

Dockerfile

update cross build image

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile

update cosign to use release v1.9.0

update cosign to use release v1.9.0

---

Dockerfile

chore: syft upgraded to v0.48.1

---

Dockerfile

feat: bump golang version to v1.18.4

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

update to use go1.17.12

---

.github/workflows/builder.yml
Dockerfile.builder

- update go in the builder image and prepare for a new release

update go in the builder image and prepare for a new release

---

Dockerfile

- update base image for go 1.17 branch

update base image for go 1.17 branch

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile
Dockerfile.builder

- Update go to 1.18.5 and support tools

Update go to 1.18.5 and support tools

---

.github/workflows/builder.yml
.github/workflows/dockerimage.yml
.github/workflows/release-golang-cross.yml
Dockerfile
Dockerfile.builder

Update go to 1.17.13 and support tools in the `go-1.17` branch

Update go to 1.17.13 and support tools

---

Dockerfile.builder

remove docker.pkg and use ghcr to match with the main branch

remove docker.pkg and use ghcr to match with the main branch

---

Dockerfile

update cosign to v1.10.1

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

start building go1.19

---

Dockerfile
Dockerfile.builder

- bump go to 1.19.1 and goreleaser to 1.11.2

bump go to 1.19.1 and goreleaser to 1.11.2

---

.github/workflows/builder.yml

update tag for builder release
missed this

update tag for builder release

---

Dockerfile

Cross-ref: https://github.com/fluxcd/source-controller/issues/899
/cc @cpanato

fix: add COSIGN_EXPERIMENTAL=1 for verify-blob

---

Dockerfile.builder
Dockerfile.osx_sdk

- bump osxcross to commit 50e86ebca7d14372febd0af8cd098705049161b9
- support osx sdk v12.3

feat: support osx sdk v12.3

---

example/.goreleaser.yml
example/go.mod
example/main.go

- fix project name of example
- update `CC` and `CXX` for build darwin binary

chore: fix fail to build example 

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

bump go to 1.19.2 and goreleaser

bump go to 1.19.2 and goreleaser

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder
example/.goreleaser.yml
example/Makefile
example/go.mod

update golang to 1.18.7 and cosign/goreleraser

update golang to 1.18.7 and cosign/goreleraser

---

Dockerfile

update base image for go 1.18.7

update base image for go 1.18.7

---

example/.goreleaser.yml

to avoid issue that we have in the past

generate sbom to test the base image

---

.github/workflows/builder.yml
.github/workflows/dockerimage.yml
.github/workflows/release-golang-cross.yml

- fix #82 
- update `set-output` via [Setting an output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

feat: disable docker login commands

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile
Dockerfile.builder

Bump golang to 1.19.3

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml

the builder-cross job failed in the signing part https://github.com/gythialy/golang-cross/actions/runs/3377451360/jobs/5606396914
this uses the digest to sign the image

use digest to sign the image

---

Dockerfile

update base builder-cross image

update base builder-cross image

---

.github/workflows/builder.yml

fix: specifies the docker file of builder

---

Dockerfile

feat: bump golang to v1.19.4

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

update go in the builder and goreleaser

---

Dockerfile

update base image for go1.18

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- bump go to 1.19.5 and goreleaser to 1.14.1

bump go to 1.19.5 and goreleaser to 1.14.1

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- bump go to 1.18.10 and goreleaser to 1.14.1

bump go to 1.18.10 and goreleaser to 1.14.1

---

Dockerfile

- update base image for go1.19

update base image for go1.19

---

.github/workflows/stale.yml
.github/workflows/welcome.yml
Dockerfile

- add welcome and stale workflow
- upgrade golang, goreleaser, buildx, pack-cli, and git-chlog to latest version

feat: bump golang to  v1.20

---

Dockerfile

update base image to use go1.20

update base image to use go1.20

---

.github/workflows/builder.yml
.github/workflows/clean-cache.yaml
.github/workflows/dockerimage.yml
.github/workflows/release-golang-cross.yml
.github/workflows/welcome.yml

- cleanup caches by a branch
- fix welcome workflow

feat: clean build cache when PR closed

---

Dockerfile

1.15.2 goreleaser

---

Dockerfile

0.71.0 syft

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

update go to 1.20.1

---

.github/workflows/builder.yml
.github/workflows/cron.yaml
.github/workflows/release-golang-cross.yml
Dockerfile

- add a cron job to automatically update dependencies 
- bump sigstore/cosign-installer from 2 to 3

feat: add a scheduled task to automatically update dependencies

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile

update cosign flags due to cosign v2 and also update base image
failed job: https://github.com/gythialy/golang-cross/actions/runs/4364835269

Update base image

---

.github/workflows/osx-sdk.yaml
Dockerfile.osx_sdk

Build OSX SDK by GitHub Action. And It's not tested yet.

feat: build osx SDK

---

.github/workflows/builder.yml
.github/workflows/osx-sdk.yaml
Dockerfile.builder
Dockerfile.osx_sdk

- upgrade osxcross to ref `3dcc13644cfaa3d7ea6a959acbe0f1a23cf2df72 `
- bump macOS SDK to v13

feat: bump macOS sdk to v13

---

.github/workflows/builder.yml
.github/workflows/osx-sdk.yaml
Dockerfile.builder
README.md
example/.goreleaser.yml

- format files
- update pack macOS SDK in README

feat: bump debian version to bookwarm

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- bump go to 1.21 for builder
- bump cosign and syft

bump go to 1.21 for builder and bump cosign and syft

---

Dockerfile

- update base image to use go1.21.2

update base image to use go1.21.2

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

bump Go to 1.21.3

---

Dockerfile

- update base image to use go1.21.3

update base image to use go1.21.3

---

Dockerfile

refactor: install google cloud sdk

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- bump fo use go1.21.4 / cosign and syft

bump fo use go1.21.4 / cosign and syft

---

.github/workflows/builder.yml
.github/workflows/dockerimage.yml
Dockerfile
Dockerfile.builder

- update images for go1.21.7 on branch `go-1.21`

[go-1.21] update images for go1.21.7

---

.github/workflows/builder.yml
Dockerfile.builder

build with the original commit here and was success https://github.com/gythialy/golang-cross/actions/runs/17233452189
so reverting only that change for now

revert osx cross update and add comments
