Dockerfile_builder

When compile _CGO_ program, the program may be run in [Alpine](https://alpinelinux.org/) based container which used `musl-libc` instead of `glibc`, we can static linking `musl-libc` then the program doesn't depend on `libc`.

add musl-libc for static link musl-libc as its small footprint

---

Dockerfile
Dockerfile.builder

thanks for this project! I'm using and it is pretty handy!
This PR updates Go to the latest 1.16 available which is 1.16.6 and also updates goreleaser to the latest as well which is 0.173.2

feat: update Go to be 1.16.6

---

Dockerfile

```shell
docker container run --rm --privileged \
-v $(pwd):/kink \
-v /var/run/docker.sock:/var/run/docker.sock \
-w /kink \
--entrypoint="/bin/sh" \
-e GITLAB_TOKEN=$GITLAB_TOKEN \
ghcr.io/gythialy/golang-cross:v1.16.6@sha256:a31f3981571aab561bfdc2c50bf25142f2460a47c35e76ae9d50826e3a1aabac \
-c "GITLAB_TOKEN=$GITLAB_TOKEN make release"
```
When I tried the command above I got an error while pushing my docker images defined in the `dockers` section within the `.goreleaer.yml` file, the error was saying `docker executable not found in $PATH` because the `ghcr.io/gythialy/golang-cross` image has not `Docker CLI` installed in it, so this PR is going to add `Docker CLI` to the image.

add docker cli to support docker push support of GoReleaser

---

Dockerfile
Dockerfile.builder

This PR updates Go to the latest 1.16 available which is 1.16.7
Maybe can we have a `golang-cross-builder` release as well?

feat: update Go to 1.16.7

---

Dockerfile

We need this because GoReleaser has 3 engines (Docker, Buildx, and Podman(GoReleaser pro only)) to support for building&pushing images, this PR aims to add the Buildx engine support.
> https://goreleaser.com/customization/docker/#customization
cc: @cpanato

add buildx support for GoReleaser

---

Dockerfile

update goreleaser to 1.2.4 due to an issue when generating the sbom with binaries, the list was duplicated causing an error when upload the files to GitHub release
https://github.com/goreleaser/goreleaser/releases/tag/v1.2.4

update goreleaser to 1.2.4

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile.builder

- remove secret that is not used anymore
- Update builder to use go 1.18

Update builder to use go 1.18

---

.github/workflows/builder.yml
Dockerfile.builder

- update builder to use go 1.17.9 in the go-1.17 branch
after this merges will release the builder 1.17.9-0 and then open a pr to build the go cross image for go 1.17

update builder to use go 1.17.9 in the go-1.17 branch

---

Dockerfile

- update base image
- update cosign
- update syft
- update go to 1.18.1

Update cross image for go 1.18

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile

update action and cosign image to use release 1.8.0 on the go-1.17 branch

update action and cosign image

---

Dockerfile

- use the latest cross builder image for go1.17

use the latest cross builder image for go1.17

---

.github/workflows/builder.yml
.github/workflows/release-golang-cross.yml
Dockerfile

update cosign to use release v1.9.0 on branch `go-1.17`

update cosign to use release v1.9.0

---

Dockerfile

update cross-builder to use base builder with go1.18.5
after this we can release it :)

update cross-builder to use base builder with go1.18.5

---

Dockerfile

update cosign to v1.10.1 on branch `go-1.17`

update cosign to v1.10.1

---

Dockerfile

update base image for golang builder go1.19
will cut a release after this get merged

update base image for golang builder go1.19

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- bump go1.18, goreleaser and ko in the go1.18 branch

bump go1.18, goreleaser and ko

---

Dockerfile

bump base image in go1.18 branch

bump base image

---

Dockerfile

- bump gorelease to v0.11.4
- bump go chang log to v0.15.1
- bump buildx to v0.9.1
- bump pack to v0.27.0

chore: upgrade goreleaser, git chglog, buildx and pack

---

Dockerfile
Dockerfile.builder
patch/osxcross-08-52-08.patch

feat: install the compiler rt libraries and support building images on M1 mac

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- Bump golang to 1.18.8
on the go-1.18 branch

Bump golang to 1.18.8

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

- update go 1.18 and goreleaser in the go-1.18 branch

update go 1.18 and goreleaser

---

.github/dependabot.yml
.github/workflows/builder.yml
.github/workflows/dockerimage.yml
.github/workflows/release-golang-cross.yml
Dockerfile.builder
example/go.mod
example/go.sum

- enable workflow inputs for build builder image
```yaml
inputs:
builder-tag:
description: golang cross builder tag name, with default value `v1.20.0-0`
golang-version:
description: golang version, with default value `v1.20`
osxcross-git-hash:
description: git commit hash of osx-cross project, with default value `50e86ebca7d14372febd0af8cd098705049161b9`
osx-min-version:
description: minimal macOS SDK deployment target, with default value `10.12`
```
- upgrade example mod
- enable docker build cache

feat: enable workflow inputs for building builder image

---

Dockerfile

- update base image to use go1.20.1
after we merge this will run a new release

update base image to use go1.20.1

---

Dockerfile

- update base image for go1.21 on `go-1.21` branch

[go-1.21] update base image for go1.21

---

.github/workflows/release-golang-cross.yml

tag the `latest` docker image only when create a release on the default branch.

fix: release latest tag

---

.github/workflows/cron.yaml

We can manually execute this task before releasing a new version.

refactor: disable schedule task

---

.github/workflows/builder.yml
Dockerfile
Dockerfile.builder

feat: bump golang to v1.24.3

---

Dockerfile

see https://github.com/gythialy/golang-cross/actions/runs/17234093497/job/48894762747

fix install gcloud as apt-key is deprecate
